// Package dcf reads Dyalog Component Files (.dcf) without a Dyalog
// dependency. Pure Go, complements amicable (220⌶) and codec (APLAN).
//
// The DCF outer container format is reverse-engineered from synthetic
// fixtures generated by Dyalog v20 (J=1, C=1, 64-bit). See
// adnotata/0013-dcf-outer-format.md for byte-level notes.
//
// Read-only for v1. Writes (FAPPEND/FREPLACE), checksums, and journal
// levels 2/3 are out of scope.
//
//	f, err := dcf.Open("path/to/file.dcf")
//	if err != nil { ... }
//	defer f.Close()
//
//	for _, c := range f.Components() {
//	    val, err := f.Read(c.Number)
//	    ...
//	}
package dcf

import (
	"bytes"
	"encoding/binary"
	"errors"
	"fmt"
	"io"
	"os"
	"time"

	"github.com/cursork/gritt/amicable"
)

// File constants.
const (
	fileMagic0 = 0xAA

	// fileMagic1 second-byte values encode (J, C) flags:
	//   0x0E — J=1 C=1 (default; checksums enabled)
	//   0x0C — J=1 C=0 (no per-component checksum)
	//   0x09 — J=0 C=0 (deprecated; layout differs, not supported here)
	fileMagic1JCBoth   = 0x0E
	fileMagic1JOnly    = 0x0C
	fileMagic1Neither  = 0x09

	ptr64 = 0xA4
	ptr32 = 0x94

	// headerSize is the size of the primary file header before the first
	// component block. Components begin at this offset.
	headerSize = 0x100
)

// Per-component block magic. The first and last bytes are always 0xA4
// (the 64-bit pointer-size indicator); the middle two bytes encode
// the on-disk format version and differ across Dyalog versions
// (`14 0E` for v20, `0D 0A` for older files). We auto-detect at parse
// time by scanning for any `A4 ?? ?? A4` pattern in the component
// region.
type componentMagic [4]byte

// 220⌶ type codes we recognise. Kept in sync with amicable's internal
// table. We need the codes here to compute body byte counts when
// scanning, before handing the body to amicable for full decode.
const (
	typeBool    = 0x21
	typeInt8    = 0x22
	typeInt16   = 0x23
	typeInt32   = 0x24
	typeFloat64 = 0x25
	typeChar8   = 0x27
	typeChar16  = 0x28
	typeChar32  = 0x29
	typeComplex = 0x2A
	typeDec128  = 0x2E
	typePointer = 0x06
)

// drForType returns the Dyalog ⎕DR type code for a 220⌶ type code.
// Returns 0 for unknown types.
func drForType(t byte) int {
	switch t {
	case typeBool:
		return 11
	case typeInt8:
		return 83
	case typeInt16:
		return 163
	case typeInt32:
		return 323
	case typeFloat64:
		return 645
	case typeChar8:
		return 80
	case typeChar16:
		return 160
	case typeChar32:
		return 320
	case typeComplex:
		return 1289
	case typeDec128:
		return 1287
	case typePointer:
		return 326
	}
	return 0
}

// Header holds the parsed top-level file metadata.
type Header struct {
	// Version is the Dyalog format version. 0x14 = v20.
	Version uint32

	// PtrSize is 8 for 64-bit files, 4 for 32-bit (legacy small-span).
	// v1 only supports 8.
	PtrSize int

	// FirstUsed is the lowest component number that may be live.
	FirstUsed uint32

	// NextFree is the next component number FAPPEND would allocate.
	// Live components have numbers in [FirstUsed, NextFree).
	NextFree uint32

	// CreatedAt is the file's creation timestamp.
	CreatedAt time.Time
}

// ComponentInfo describes one component without reading its body.
type ComponentInfo struct {
	// Number is the component's logical number (as used by FREAD/FREPLACE).
	Number int

	// Offset is the byte offset in the file where the primary copy of
	// this component's block begins.
	Offset int64

	// BlockSize is the value of the block's size_u32 field. Not the
	// number of bytes the block occupies on disk — that's larger
	// (includes the journal copy and inter-copy padding).
	BlockSize uint32

	// DR is the Dyalog ⎕DR type code of the array.
	DR int

	// Rank is the array's rank.
	Rank int

	// Shape is the array's shape vector.
	Shape []int

	// WrittenAt is the component's last-write timestamp, if recoverable
	// from the block header. Zero if not parseable.
	WrittenAt time.Time
}

// File is an opened DCF.
type File struct {
	data       []byte
	header     Header
	components []ComponentInfo
	magic      componentMagic

	// Diagnostics — populated during scan, surfaced to callers via
	// the ScanReport accessor. Lets tools (apldcf, the TUI) tell the
	// user *why* fewer components were found than the header expects.
	scanReport ScanReport
}

// ScanReport captures what happened during component discovery.
// Useful for surfacing partial-success cases to the user instead of
// silently dropping components.
type ScanReport struct {
	// MagicHits is the total number of per-component magic patterns
	// found in the data region (each component appears more than once
	// — primary + journal + sometimes backup-region copies).
	MagicHits int

	// ParseFailures is the number of magic hits whose surrounding
	// metadata couldn't be parsed as a valid component header (bad
	// magic offset, implausible shape, etc.). Usually means an older
	// on-disk format the parser doesn't fully understand.
	ParseFailures int

	// Deduplicated is the number of magic hits collapsed into existing
	// components by the journal/backup dedup logic.
	Deduplicated int

	// MagicVariant captures the detected per-component magic bytes.
	// `A4 14 0E A4` for v20; older Dyalog versions use different
	// middle bytes (e.g. `A4 0D 0A A4` for v13-era files).
	MagicVariant [4]byte

	// IsKnownVariant is true only when MagicVariant matches a format
	// we've validated against. Today: just v20.
	IsKnownVariant bool
}

// ScanReport returns the diagnostics collected during component
// discovery.
func (f *File) ScanReport() ScanReport { return f.scanReport }

// Open reads and parses a DCF file. The whole file is held in memory.
// For very large files this is wasteful — we'll add mmap later if it
// matters.
func Open(path string) (*File, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	return parse(data)
}

// OpenReader parses a DCF from a Reader. Used in tests; allocates.
func OpenReader(r io.Reader) (*File, error) {
	data, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}
	return parse(data)
}

// Header returns parsed file-header metadata.
func (f *File) Header() Header { return f.header }

// Components returns metadata for every live component, in component-
// number order.
func (f *File) Components() []ComponentInfo { return f.components }

// Close releases resources. Currently a no-op (we hold a byte slice),
// but kept for forward compatibility with an mmap-backed File.
func (f *File) Close() error { return nil }

// ReplaceBody overwrites the body bytes of component n in every block
// copy (primary + journal + backup region). The caller is responsible
// for producing newBody with the same length as the current body — a
// mismatch is rejected. The file's component metadata (type, rank,
// shape) is unchanged.
//
// Restrictions for v1:
//   - Same-size only: len(newBody) must equal the existing body length.
//   - Files with checksums enabled (C=1) are refused: we'd need to
//     recompute Dyalog's per-component checksum, which is a separate
//     reverse-engineering pass. See FACIENDA "DCF writes".
//
// On success, ReplaceBody updates File.data in memory. Persist the
// change via WriteTo or Save.
func (f *File) ReplaceBody(n int, newBody []byte) error {
	var c *ComponentInfo
	for i := range f.components {
		if f.components[i].Number == n {
			c = &f.components[i]
			break
		}
	}
	if c == nil {
		return fmt.Errorf("dcf: component %d not found", n)
	}

	// Compute the existing body length and offset within the primary
	// block.
	d := f.data
	off := int(c.Offset)
	tr := binary.LittleEndian.Uint16(d[off+0x20 : off+0x22])
	rankFlags := byte(tr & 0xFF)
	typeCode := byte(tr >> 8)
	if rankFlags&0x08 == 0 {
		return errors.New("dcf: writes to nested arrays not yet supported")
	}
	nElem := 1
	for _, s := range c.Shape {
		nElem *= s
	}
	oldBodyBytes, err := bodySize(typeCode, nElem, rankFlags)
	if err != nil {
		return err
	}
	if len(newBody) != oldBodyBytes {
		return fmt.Errorf("dcf: replace requires same-size body (have %d, got %d)", oldBodyBytes, len(newBody))
	}

	// Refuse C=1 files: their per-component checksum needs to be
	// recomputed when the body changes, and we haven't reversed the
	// algorithm yet. The file-header byte 1 distinguishes:
	//   0x0E → C=1 (refuse)
	//   0x0C → C=0 (allow)
	if d[1] == fileMagic1JCBoth {
		return errors.New("dcf: refusing to write to a checksum-enabled (C=1) file — set C=0 via ⎕FPROPS before edit, or wait for proper checksum support")
	}

	// Find every copy of this component's block (primary, journal,
	// backup region) by scanning for the per-component magic at the
	// same relative content offset. Each copy gets its body region
	// overwritten.
	overwriteAt := func(blockOff int) {
		bodyStart := blockOff + 0x28 + c.Rank*8
		if bodyStart+len(newBody) > len(d) {
			return
		}
		copy(d[bodyStart:bodyStart+len(newBody)], newBody)
	}
	overwriteAt(off)

	// Scan forward from the primary for any other copies of this
	// component. We identify "the same component" by matching the
	// block's type_rank + shape against the primary's. This catches
	// journal copies (right after primary) and backup-region copies
	// (later in the file) without us needing to know their exact
	// offsets in advance.
	pos := off + 4
	for pos+8 < len(d) {
		idx := indexBytes(d[pos:], f.magic[:])
		if idx < 0 {
			break
		}
		copyBlock := pos + idx - 4
		if copyBlock+0x28+c.Rank*8 > len(d) {
			break
		}
		// Same type_rank?
		copyTR := binary.LittleEndian.Uint16(d[copyBlock+0x20 : copyBlock+0x22])
		if copyTR == tr {
			// Same shape?
			same := true
			for i, s := range c.Shape {
				v := binary.LittleEndian.Uint64(d[copyBlock+0x28+i*8 : copyBlock+0x28+(i+1)*8])
				if int(v) != s {
					same = false
					break
				}
			}
			if same {
				overwriteAt(copyBlock)
			}
		}
		pos = pos + idx + 4
	}
	return nil
}

// indexBytes is bytes.Index extracted so ReplaceBody doesn't pull in
// the import (it's already used at the top of the file).
func indexBytes(haystack, needle []byte) int {
	return bytes.Index(haystack, needle)
}

// WriteTo persists the file's current in-memory state to path. Use
// after ReplaceBody to commit edits to disk.
func (f *File) WriteTo(path string) error {
	return os.WriteFile(path, f.data, 0o644)
}

// MarshalBody runs the value through amicable.Marshal and returns just
// the body bytes — strips the 220⌶ outer envelope (magic + size +
// type_rank + shape). This is the byte form a component's body takes
// inside a DCF block.
//
// Callers pass the result to File.ReplaceBody. If the value's marshalled
// type/rank/shape differ from the component being replaced, the body
// length will likely differ too and ReplaceBody will reject it.
func MarshalBody(v any) ([]byte, error) {
	wire, err := amicable.Marshal(v)
	if err != nil {
		return nil, err
	}
	// 220⌶ root envelope: 2 magic + ptrSize size + 1 rank_flags + 1
	// type + (ptrSize-2) pad + rank × ptrSize shape, then body.
	const ptrSize = 8
	if len(wire) < 2+ptrSize+ptrSize {
		return nil, errors.New("dcf: marshalled output too short to strip envelope")
	}
	rankFlags := wire[2+ptrSize]
	rank := int(rankFlags >> 4)
	headerLen := 2 + ptrSize + ptrSize + rank*ptrSize
	if headerLen > len(wire) {
		return nil, errors.New("dcf: marshalled output too short for declared rank")
	}
	return wire[headerLen:], nil
}

// Read returns the deserialised value of component n. Returns an error
// if n is not a live component or the body cannot be parsed.
func (f *File) Read(n int) (any, error) {
	for _, c := range f.components {
		if c.Number == n {
			return f.readBody(c)
		}
	}
	return nil, fmt.Errorf("dcf: component %d not found", n)
}

func parse(data []byte) (*File, error) {
	if len(data) < headerSize {
		return nil, errors.New("dcf: file too short for header")
	}
	if data[0] != fileMagic0 {
		return nil, fmt.Errorf("dcf: bad magic byte 0 0x%02X (want AA)", data[0])
	}
	switch data[1] {
	case fileMagic1JCBoth, fileMagic1JOnly:
		// supported
	case fileMagic1Neither:
		return nil, errors.New("dcf: J=0 C=0 files (magic AA09) have a different layout we don't support yet")
	default:
		return nil, fmt.Errorf("dcf: unknown magic byte 1 0x%02X", data[1])
	}
	h := Header{}
	h.Version = binary.LittleEndian.Uint32(data[2:6])
	switch data[6] {
	case ptr64:
		h.PtrSize = 8
	case ptr32:
		return nil, errors.New("dcf: 32-bit small-span files not supported")
	default:
		return nil, fmt.Errorf("dcf: unknown ptr-size byte 0x%02X", data[6])
	}
	h.FirstUsed = binary.LittleEndian.Uint32(data[0x08:0x0C])
	h.NextFree = binary.LittleEndian.Uint32(data[0x10:0x14])
	// File creation timestamp at 0x78..0x7F. Unix seconds in the low
	// 32 bits (the high 32 are zero in v20 files). Per-component
	// timestamps in FHIST/FRDCI use 60ths-of-a-second; the file-level
	// stamp does not.
	ts := binary.LittleEndian.Uint32(data[0x78:0x7C])
	if ts != 0 {
		h.CreatedAt = time.Unix(int64(ts), 0).UTC()
	}

	f := &File{data: data, header: h}
	if err := f.scanComponents(); err != nil {
		return nil, err
	}
	return f, nil
}

// scanComponents discovers component blocks in the primary region by
// scanning forward from the header for the per-component magic. It
// deduplicates journal/backup copies and assigns logical component
// numbers in encounter order.
//
// This is the v1 strategy described in adnotata/0013. Once we decode
// the component directory in the header it can be replaced with an
// indexed lookup.
func (f *File) scanComponents() error {
	want := int(int64(f.header.NextFree) - int64(f.header.FirstUsed))
	if want <= 0 {
		return nil
	}

	// Auto-detect the per-file component magic by finding the first
	// A4..A4 pattern at or after headerSize.
	if !f.detectMagic() {
		return errors.New("dcf: could not detect per-component magic")
	}
	f.scanReport.MagicVariant = f.magic
	f.scanReport.IsKnownVariant = f.magic[1] == 0x14 && f.magic[2] == 0x0E

	seen := make(map[string]bool)
	pos := headerSize
	for pos+8 < len(f.data) && len(f.components) < want {
		idx := bytes.Index(f.data[pos:], f.magic[:])
		if idx < 0 {
			break
		}
		blockStart := pos + idx - 4
		if blockStart < headerSize {
			pos = pos + idx + 4
			continue
		}
		f.scanReport.MagicHits++
		c, err := f.parseComponentHeader(blockStart)
		if err != nil {
			f.scanReport.ParseFailures++
			pos = pos + idx + 4
			continue
		}
		fp := componentFingerprint(c, f.data)
		if seen[fp] {
			f.scanReport.Deduplicated++
		} else {
			seen[fp] = true
			c.Number = int(f.header.FirstUsed) + len(f.components)
			f.components = append(f.components, c)
		}
		pos = pos + idx + 4
	}
	return nil
}

// detectMagic scans for the first A4..A4 pattern at or after the file
// header. The 4 bytes become the per-file component magic, allowing
// the same parser to handle different Dyalog on-disk versions.
func (f *File) detectMagic() bool {
	for i := headerSize; i+4 <= len(f.data); i++ {
		if f.data[i] == 0xA4 && f.data[i+3] == 0xA4 {
			f.magic = componentMagic{f.data[i], f.data[i+1], f.data[i+2], f.data[i+3]}
			return true
		}
	}
	return false
}

// parseComponentHeader reads a per-component block header at offset
// `off` and fills a ComponentInfo with shape/type metadata but does
// not read the body.
func (f *File) parseComponentHeader(off int) (ComponentInfo, error) {
	d := f.data
	if off+0x30 > len(d) {
		return ComponentInfo{}, errors.New("dcf: block header past EOF")
	}
	if d[off+4] != f.magic[0] || d[off+5] != f.magic[1] ||
		d[off+6] != f.magic[2] || d[off+7] != f.magic[3] {
		return ComponentInfo{}, errors.New("dcf: bad block magic")
	}
	c := ComponentInfo{
		Offset:    int64(off),
		BlockSize: binary.LittleEndian.Uint32(d[off : off+4]),
	}
	// Per-component write timestamp lives in the same slot as the
	// file's CreatedAt (block offset +0x10..+0x18 — but on a 4-byte
	// aligned scheme the per-component timestamp is at block+0x10
	// as u32 only). Use the file-level timestamp for now; per-block
	// timestamp decode is fuzzy.
	c.WrittenAt = f.header.CreatedAt

	// type_rank at block+0x20, low byte = (rank<<4)|flags, high byte = type.
	tr := binary.LittleEndian.Uint16(d[off+0x20 : off+0x22])
	rankFlags := byte(tr & 0xFF)
	typeCode := byte(tr >> 8)
	c.Rank = int(rankFlags >> 4)
	c.DR = drForType(typeCode)
	if c.DR == 0 {
		return c, fmt.Errorf("dcf: unknown type code 0x%02X", typeCode)
	}

	// Shape at block+0x28, rank × u64.
	shapeOff := off + 0x28
	if shapeOff+c.Rank*8 > len(d) {
		return c, errors.New("dcf: shape past EOF")
	}
	// Reasonable upper bound: no single dimension exceeds 2^31. Larger
	// values almost certainly mean we're reading the wrong bytes
	// (e.g. older Dyalog on-disk format with a different metadata
	// layout). Bail rather than emit garbage.
	c.Shape = make([]int, c.Rank)
	for i := 0; i < c.Rank; i++ {
		raw := binary.LittleEndian.Uint64(d[shapeOff+i*8 : shapeOff+i*8+8])
		if raw > 1<<31 {
			return c, fmt.Errorf("dcf: implausible shape[%d]=%d (likely wrong layout for this file's format version)", i, int64(raw))
		}
		c.Shape[i] = int(raw)
	}
	return c, nil
}

// readBody parses the component's array body. It synthesises a 220⌶
// envelope around the block's data and hands it to amicable, so all
// type decoding (including nested arrays and namespaces) is centralised.
func (f *File) readBody(c ComponentInfo) (any, error) {
	d := f.data
	off := int(c.Offset)
	// Re-read type so we can synthesise the envelope.
	tr := binary.LittleEndian.Uint16(d[off+0x20 : off+0x22])
	rankFlags := byte(tr & 0xFF)
	typeCode := byte(tr >> 8)

	// Element count from product of shape, with the special case of a
	// rank-0 scalar (product over empty shape = 1 element).
	nElem := 1
	for _, s := range c.Shape {
		nElem *= s
	}

	bodyOff := off + 0x28 + c.Rank*8
	if bodyOff > len(d) {
		return nil, fmt.Errorf("dcf: body of component %d starts past EOF", c.Number)
	}
	// Body byte size depends on type. For simple types we precompute;
	// for nested arrays the children are variable-sized so we hand
	// amicable an open-ended slice and let its structural parser stop
	// after reading the declared number of children.
	var body []byte
	if rankFlags&0x08 == 0 {
		// Nested (per amicable's bit semantics: 0x08 clear = nested).
		body = d[bodyOff:]
	} else {
		bodyBytes, err := bodySize(typeCode, nElem, rankFlags)
		if err != nil {
			return nil, err
		}
		if bodyOff+bodyBytes > len(d) {
			return nil, fmt.Errorf("dcf: body of component %d extends past EOF", c.Number)
		}
		body = d[bodyOff : bodyOff+bodyBytes]
	}

	// Synthesise a 220⌶ stream. Layout from 0010-:
	//   [df a4] [size:8] [rank_flags:1] [type:1] [pad to 8] [shape: rank*8] [body padded to 8]
	// size = 3 + rank + nElem for nested, otherwise computed.
	envelope := build220Envelope(rankFlags, typeCode, c.Shape, body)
	return amicable.Unmarshal(envelope)
}

// bodySize returns the byte size of a packed array body for the given
// 220⌶ type code and element count. Pads to 8-byte alignment. Only
// valid for simple (non-nested) arrays — readBody handles nested via
// a separate path.
func bodySize(typeCode byte, nElem int, rankFlags byte) (int, error) {
	var n int
	switch typeCode {
	case typeBool:
		n = (nElem + 7) / 8
	case typeInt8, typeChar8:
		n = nElem
	case typeInt16, typeChar16:
		n = nElem * 2
	case typeInt32, typeChar32:
		n = nElem * 4
	case typeFloat64:
		n = nElem * 8
	case typeComplex, typeDec128:
		n = nElem * 16
	default:
		return 0, fmt.Errorf("dcf: cannot size body for type 0x%02X", typeCode)
	}
	// Pad to 8-byte boundary.
	if r := n % 8; r != 0 {
		n += 8 - r
	}
	return n, nil
}

// build220Envelope wraps an array body in a 220⌶ stream so amicable
// can decode it. Returns the byte slice.
func build220Envelope(rankFlags, typeCode byte, shape []int, body []byte) []byte {
	// 220⌶ root: [df a4] [size:8] [rank_flags:1] [type:1] [pad to 8 ptr] [shape:rank*8] [body]
	// size field: total_root_bytes = 2 + (size − 1) × ptrSize  (simple arrays, per 0010-)
	// solve for size: size = (total_root_bytes - 2) / ptrSize + 1
	// total = 2 (magic) + 8 (size) + 8 (rank+type+pad) + len(shape)*8 + len(body)
	rank := len(shape)
	total := 2 + 8 + 8 + rank*8 + len(body)
	sizeField := uint64((total-2)/8 + 1)

	buf := make([]byte, 0, total)
	buf = append(buf, 0xDF, 0xA4)
	szBytes := make([]byte, 8)
	binary.LittleEndian.PutUint64(szBytes, sizeField)
	buf = append(buf, szBytes...)
	buf = append(buf, rankFlags, typeCode)
	buf = append(buf, 0, 0, 0, 0, 0, 0) // pad to 8 after the 2-byte type_rank
	for _, s := range shape {
		sb := make([]byte, 8)
		binary.LittleEndian.PutUint64(sb, uint64(s))
		buf = append(buf, sb...)
	}
	buf = append(buf, body...)
	return buf
}

// componentFingerprint produces a string uniquely identifying a
// component's content, used to dedupe journal/backup copies.
func componentFingerprint(c ComponentInfo, data []byte) string {
	tr := binary.LittleEndian.Uint16(data[int(c.Offset)+0x20 : int(c.Offset)+0x22])
	// Pack rank/type/shape into a stable string. Don't include body —
	// the journal copy *is* the same body, so type+shape is enough.
	b := make([]byte, 0, 16+8*len(c.Shape))
	b = binary.LittleEndian.AppendUint16(b, tr)
	for _, s := range c.Shape {
		b = binary.LittleEndian.AppendUint64(b, uint64(s))
	}
	b = binary.LittleEndian.AppendUint32(b, c.BlockSize)
	return string(b)
}

// ticksToTime converts 60ths-of-a-second since 1970-01-01 UTC to a
// time.Time. Matches the units used by ⎕FHIST and ⎕FRDCI.
func ticksToTime(ticks uint64) time.Time { //nolint:unused
	secs := int64(ticks / 60)
	frac := int64(ticks%60) * (int64(time.Second) / 60)
	return time.Unix(secs, frac).UTC()
}
